name: icon_font_gen
version: 0.0.1
homepage: https://github.com/jheimes-silveira/icon_font_gen
description: Convert all *.svg icons from dir to icon-font (.ttf) and generates flutter compatible dart class.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  recase: ^4.0.0
  args: ^2.3.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  lints: ^2.0.1

executables:
  icon_font_gen: icon_font_gen
